default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pictagram_development

test:
  <<: *default
  database: pictagram_test

production:
  <<: *default
  database: pictagram_production
  username: pictagram
  password: <%= ENV['PICTAGRAM_DATABASE_PASSWORD'] %>